// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef FeedbackDlg_h
#define FeedbackDlg_h
#include <FL/Fl.H>
#define MR_OK 0
#define MR_CANCEL 1
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>

class CFeedbackDlg {
public:
  CFeedbackDlg();
  Fl_Double_Window *wndProcessing;
  ~CFeedbackDlg();
  void show();
  void hide();
};
#endif
