// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "NodePropDlg.h"

void CNodePropDlg::cb_btnApply_i(Fl_Button*, void*) {
  if (m_node!=NULL)
{
	m_node->setPosition(
		edtXCoord->value(),
		edtYCoord->value(),
		edtZCoord->value());
	if (m_workspace!=NULL)
	{
		m_workspace->set_changed();
		m_workspace->redraw();
	}
};
}
void CNodePropDlg::cb_btnApply(Fl_Button* o, void* v) {
  ((CNodePropDlg*)(o->parent()->user_data()))->cb_btnApply_i(o,v);
}

void CNodePropDlg::cb_btnClose_i(Fl_Button*, void*) {
  wndNodeProp->hide();
}
void CNodePropDlg::cb_btnClose(Fl_Button* o, void* v) {
  ((CNodePropDlg*)(o->parent()->user_data()))->cb_btnClose_i(o,v);
}

CNodePropDlg::CNodePropDlg() {
  { wndNodeProp = new Fl_Double_Window(178, 261, "Node properties");
    wndNodeProp->user_data((void*)(this));
    { btnApply = new Fl_Button(105, 231, 67, 25, "Apply");
      btnApply->box(FL_PLASTIC_UP_BOX);
      btnApply->down_box(FL_PLASTIC_DOWN_BOX);
      btnApply->labelsize(12);
      btnApply->callback((Fl_Callback*)cb_btnApply);
    } // Fl_Button* btnApply
    { grpWorkspace = new Fl_Group(4, 19, 169, 96, "Coordinates");
      grpWorkspace->box(FL_PLASTIC_DOWN_FRAME);
      grpWorkspace->labelsize(12);
      grpWorkspace->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      { edtXCoord = new Fl_Value_Input(90, 26, 74, 24, "X-Coordinate");
        edtXCoord->box(FL_PLASTIC_DOWN_BOX);
        edtXCoord->labelsize(12);
        edtXCoord->minimum(-1e+300);
        edtXCoord->maximum(1e+300);
        edtXCoord->textsize(12);
      } // Fl_Value_Input* edtXCoord
      { edtZCoord = new Fl_Value_Input(90, 82, 74, 25, "Z-Coordinate");
        edtZCoord->box(FL_PLASTIC_DOWN_BOX);
        edtZCoord->labelsize(12);
        edtZCoord->textsize(12);
      } // Fl_Value_Input* edtZCoord
      { edtYCoord = new Fl_Value_Input(90, 54, 74, 25, "Y-Coordinate");
        edtYCoord->box(FL_PLASTIC_DOWN_BOX);
        edtYCoord->labelsize(12);
        edtYCoord->textsize(12);
      } // Fl_Value_Input* edtYCoord
      grpWorkspace->end();
    } // Fl_Group* grpWorkspace
    { btnClose = new Fl_Button(38, 231, 61, 25, "Close");
      btnClose->box(FL_PLASTIC_UP_BOX);
      btnClose->down_box(FL_PLASTIC_DOWN_BOX);
      btnClose->labelsize(12);
      btnClose->callback((Fl_Callback*)cb_btnClose);
    } // Fl_Button* btnClose
    { grpDisplacements = new Fl_Group(5, 132, 168, 93, "Computed displacements");
      grpDisplacements->box(FL_PLASTIC_DOWN_FRAME);
      grpDisplacements->labelsize(12);
      grpDisplacements->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      { edtXDispl = new Fl_Value_Input(87, 138, 78, 25, "X-Displ.");
        edtXDispl->box(FL_PLASTIC_DOWN_BOX);
        edtXDispl->labelsize(12);
        edtXDispl->minimum(-1e+300);
        edtXDispl->maximum(1e+300);
        edtXDispl->textsize(12);
      } // Fl_Value_Input* edtXDispl
      { edtYDispl = new Fl_Value_Input(87, 166, 78, 25, "Y-Displ.");
        edtYDispl->box(FL_PLASTIC_DOWN_BOX);
        edtYDispl->labelsize(12);
        edtYDispl->minimum(-1e+300);
        edtYDispl->maximum(1e+300);
        edtYDispl->textsize(12);
      } // Fl_Value_Input* edtYDispl
      { edtZDispl = new Fl_Value_Input(87, 194, 78, 25, "Z-Displ.");
        edtZDispl->box(FL_PLASTIC_DOWN_BOX);
        edtZDispl->labelsize(12);
        edtZDispl->minimum(-1e+300);
        edtZDispl->maximum(1e+300);
        edtZDispl->textsize(12);
      } // Fl_Value_Input* edtZDispl
      grpDisplacements->end();
    } // Fl_Group* grpDisplacements
    wndNodeProp->set_non_modal();
    wndNodeProp->end();
  } // Fl_Double_Window* wndNodeProp
  m_node = NULL;
}

void CNodePropDlg::show() {
  this->setNode(m_node);
  wndNodeProp->show();
}

void CNodePropDlg::setNode(CIvfFemNode* node) {
  m_node = node;
  if (m_node==NULL)
  {
  	edtXCoord->deactivate();
  	edtYCoord->deactivate();
  	edtZCoord->deactivate();
  	edtXDispl->deactivate();
  	edtYDispl->deactivate();
  	edtZDispl->deactivate();
  	btnApply->deactivate();
  	edtXCoord->value(0);
  	edtYCoord->value(0);
  	edtZCoord->value(0);
  	edtXDispl->value(0);
  	edtYDispl->value(0);
  	edtZDispl->value(0);
  }
  else
  {
  	edtXCoord->activate();
  	edtYCoord->activate();
  	edtZCoord->activate();
  	edtXDispl->activate();
  	edtYDispl->activate();
  	edtZDispl->activate();
  	btnApply->activate();
  	double x, y, z;
  	double dx, dy, dz;
  	m_node->getPosition(x, y, z);
  	dx = m_node->getFemNode()->getValue(0);
  	dy = m_node->getFemNode()->getValue(1);
  	dz = m_node->getFemNode()->getValue(2);
  	edtXCoord->value(x);
  	edtYCoord->value(y);
  	edtZCoord->value(z);
  	edtXDispl->value(dx);
  	edtYDispl->value(dy);
  	edtZDispl->value(dz);
  }
}

CIvfFemNode* CNodePropDlg::getNode() {
  return m_node;
}

void CNodePropDlg::setWorkspace(Fl_Widget* widget) {
  m_workspace = widget;
}

void CNodePropDlg::hide() {
  wndNodeProp->hide();
}
