// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef ElementLoadDlg_h
#define ElementLoadDlg_h
#include <FL/Fl.H>
#define MR_OK 0
#define MR_CANCEL 1
#include <FemBeamLoad.h>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Round_Button.H>

class ElementLoadDlg {
  FemBeamLoad* m_load;
  Fl_Widget* m_workspace;
  int m_modalResult;
  Fl_Color m_colorIndex;
public:
  ElementLoadDlg();
  Fl_Double_Window *wndElementLoad;
  Fl_Button *btnApply;
private:
  inline void cb_btnApply_i(Fl_Button*, void*);
  static void cb_btnApply(Fl_Button*, void*);
public:
  Fl_Button *btnClose;
private:
  inline void cb_btnClose_i(Fl_Button*, void*);
  static void cb_btnClose(Fl_Button*, void*);
public:
  Fl_Tabs *tbElementLoad;
  Fl_Group *grpGeneral;
  Fl_Input *edtName;
  Fl_Box *boxColor;
  Fl_Button *btnSetColor;
private:
  inline void cb_btnSetColor_i(Fl_Button*, void*);
  static void cb_btnSetColor(Fl_Button*, void*);
public:
  Fl_Group *grpData;
  Fl_Value_Input *edtValue;
  Fl_Group *grpLoadDirection;
  Fl_Round_Button *rbXDirection;
  Fl_Round_Button *rbYDirection;
  Fl_Round_Button *rbZDirection;
  void show();
  void setLoad(FemBeamLoad* load);
  FemBeamLoad* getLoad();
  void setWorkspace(Fl_Widget* widget);
  void hide();
  int getModalResult();
};
#endif
