// generated by Fast Light User Interface Designer (fluid) version 1.0100

#include "FeedbackDlg.h"

CFeedbackDlg::CFeedbackDlg() {
  Fl_Window* w;
  { Fl_Window* o = wndProcessing = new Fl_Window(406, 73, "Objective frame");
    w = o;
    o->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(0, 0, 406, 73, "Precalculating...");
      o->box(FL_PLASTIC_UP_BOX);
      o->labelfont(2);
      o->labelsize(44);
    }
    o->set_modal();
    o->clear_border();
    o->end();
  }
}

CFeedbackDlg::~CFeedbackDlg() {
  delete wndProcessing;
}

void CFeedbackDlg::show() {
  wndProcessing->position(Fl::w()/2-wndProcessing->w()/2,Fl::h()/2-wndProcessing->h()/2);
wndProcessing->show();
}

void CFeedbackDlg::hide() {
  wndProcessing->hide();
}
