// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "WorkspaceDlg.h"
#include <iostream.h>

void CWorkspaceDlg::cb_btnOk_i(Fl_Button*, void*) {
  m_modalResult = MR_OK;
wndWorkspace->hide();
m_workspaceSize = (double)(sldWorkspaceSize->value());
}
void CWorkspaceDlg::cb_btnOk(Fl_Button* o, void* v) {
  ((CWorkspaceDlg*)(o->parent()->user_data()))->cb_btnOk_i(o,v);
}

void CWorkspaceDlg::cb_btnCancel_i(Fl_Button*, void*) {
  m_modalResult = MR_CANCEL;
wndWorkspace->hide();
}
void CWorkspaceDlg::cb_btnCancel(Fl_Button* o, void* v) {
  ((CWorkspaceDlg*)(o->parent()->user_data()))->cb_btnCancel_i(o,v);
}

CWorkspaceDlg::CWorkspaceDlg() {
  { wndWorkspace = new Fl_Double_Window(309, 186, "Workspace");
    wndWorkspace->user_data((void*)(this));
    { btnOk = new Fl_Button(236, 6, 67, 25, "OK");
      btnOk->box(FL_PLASTIC_UP_BOX);
      btnOk->down_box(FL_PLASTIC_DOWN_BOX);
      btnOk->callback((Fl_Callback*)cb_btnOk);
    } // Fl_Button* btnOk
    { btnCancel = new Fl_Button(236, 37, 67, 25, "Cancel");
      btnCancel->box(FL_PLASTIC_UP_BOX);
      btnCancel->down_box(FL_PLASTIC_DOWN_BOX);
      btnCancel->callback((Fl_Callback*)cb_btnCancel);
    } // Fl_Button* btnCancel
    { grpWorkspace = new Fl_Group(5, 5, 225, 175);
      grpWorkspace->box(FL_PLASTIC_DOWN_FRAME);
      { sldWorkspaceSize = new Fl_Value_Slider(17, 28, 201, 20, "Size (units)");
        sldWorkspaceSize->type(5);
        sldWorkspaceSize->box(FL_PLASTIC_DOWN_BOX);
        sldWorkspaceSize->labelsize(12);
        sldWorkspaceSize->minimum(1);
        sldWorkspaceSize->maximum(100);
        sldWorkspaceSize->step(1);
        sldWorkspaceSize->value(10);
        sldWorkspaceSize->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      } // Fl_Value_Slider* sldWorkspaceSize
      { sldNodeSize = new Fl_Value_Slider(17, 68, 201, 20, "Node size (% of workspace)");
        sldNodeSize->type(5);
        sldNodeSize->box(FL_PLASTIC_DOWN_BOX);
        sldNodeSize->labelsize(12);
        sldNodeSize->minimum(0.1);
        sldNodeSize->maximum(2);
        sldNodeSize->step(0.05);
        sldNodeSize->value(0.5);
        sldNodeSize->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      } // Fl_Value_Slider* sldNodeSize
      { sldLineRadius = new Fl_Value_Slider(17, 107, 201, 20, "Line radius (% of workspace)");
        sldLineRadius->type(5);
        sldLineRadius->box(FL_PLASTIC_DOWN_BOX);
        sldLineRadius->labelsize(12);
        sldLineRadius->minimum(0.1);
        sldLineRadius->maximum(2);
        sldLineRadius->step(0.05);
        sldLineRadius->value(0.15);
        sldLineRadius->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      } // Fl_Value_Slider* sldLineRadius
      { sldLoadSize = new Fl_Value_Slider(18, 146, 201, 20, "Load size (% of workspace)");
        sldLoadSize->type(5);
        sldLoadSize->box(FL_PLASTIC_DOWN_BOX);
        sldLoadSize->labelsize(12);
        sldLoadSize->minimum(1);
        sldLoadSize->maximum(10);
        sldLoadSize->step(1);
        sldLoadSize->value(7);
        sldLoadSize->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      } // Fl_Value_Slider* sldLoadSize
      grpWorkspace->end();
    } // Fl_Group* grpWorkspace
    wndWorkspace->set_modal();
    wndWorkspace->end();
  } // Fl_Double_Window* wndWorkspace
}

CWorkspaceDlg::~CWorkspaceDlg() {
  delete wndWorkspace;
}

void CWorkspaceDlg::show() {
  wndWorkspace->show();
  while (wndWorkspace->visible()) Fl::wait();
}

int CWorkspaceDlg::getModalResult() {
  return m_modalResult;
}

void CWorkspaceDlg::setWorkspaceSize(double size) {
  m_workspaceSize = size;
  sldWorkspaceSize->value(size);
}

double CWorkspaceDlg::getWorkspaceSize() {
  return m_workspaceSize;
}

void CWorkspaceDlg::setNodeSize(double size) {
  sldNodeSize->value(size*100.0);
}

void CWorkspaceDlg::setLineRadius(double radius) {
  sldLineRadius->value(radius*100.0);
}

void CWorkspaceDlg::setLoadSize(double size) {
  sldLoadSize->value(size*100.0);
}

double CWorkspaceDlg::getNodeSize() {
  return (double)sldNodeSize->value()/100.0;
}

double CWorkspaceDlg::getLineRadius() {
  return (double)sldLineRadius->value()/100.0;
}

double CWorkspaceDlg::getLoadSize() {
  return (double)sldLoadSize->value()/100.0;
}
