// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef NodeLoadsDlg_h
#define NodeLoadsDlg_h
#include <FL/Fl.H>
#define MR_OK 0
#define MR_CANCEL 1
#include <FL/fl_message.H>
#include <FemNodeLoadSet.h>
#include <FemBeamNodeLoad.h>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Browser.H>
#include "Fl_HoverButton.h"

class CNodeLoadsDlg {
    CFemNodeLoadSet* m_loadSet;
    void* m_femWidget;
    CFemBeamNodeLoad* m_currentLoad;
public:
    CNodeLoadsDlg();
    Fl_Double_Window *wndNodeLoads;
    Fl_Browser *lbLoadSet;
private:
    void cb_lbLoadSet_i(Fl_Browser*, void*);
    static void cb_lbLoadSet(Fl_Browser*, void*);
public:
    Fl_HoverButton *btnAddLoad;
private:
    void cb_btnAddLoad_i(Fl_HoverButton*, void*);
    static void cb_btnAddLoad(Fl_HoverButton*, void*);
public:
    Fl_HoverButton *btnRemoveLoad;
private:
    void cb_btnRemoveLoad_i(Fl_HoverButton*, void*);
    static void cb_btnRemoveLoad(Fl_HoverButton*, void*);
public:
    Fl_HoverButton *btnEditLoad;
private:
    void cb_btnEditLoad_i(Fl_HoverButton*, void*);
    static void cb_btnEditLoad(Fl_HoverButton*, void*);
public:
    Fl_HoverButton *btnAssignLoad;
private:
    void cb_btnAssignLoad_i(Fl_HoverButton*, void*);
    static void cb_btnAssignLoad(Fl_HoverButton*, void*);
public:
    Fl_HoverButton *btnClearElements;
private:
    void cb_btnClearElements_i(Fl_HoverButton*, void*);
    static void cb_btnClearElements(Fl_HoverButton*, void*);
public:
    void show();
    void setLoadSet(CFemNodeLoadSet* loadSet);
    CFemNodeLoadSet* getLoadSet();
    void hide();
private:
    void fillListBox();
public:
    CFemBeamNodeLoad* getCurrentLoad();
    void setFemWidget(void* femWidget);
};
#endif
