// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef ElementLoadsDlg_h
#define ElementLoadsDlg_h
#include <FL/Fl.H>
#define MR_OK 0
#define MR_CANCEL 1
#ifdef WIN32
#include "fl_message_win.H"
#endif
#include <FL/fl_message.H>
#include <FemElementLoadSet.h>
#include <FemBeamLoad.h>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Browser.H>
#include "Fl_HoverButton.h"

class ElementLoadsDlg {
  ElementLoadSet* m_loadSet;
  void* m_femWidget;
  BeamLoad* m_currentLoad;
public:
  ElementLoadsDlg();
  Fl_Double_Window *wndElementLoads;
  Fl_Browser *lbLoadSet;
private:
  inline void cb_lbLoadSet_i(Fl_Browser*, void*);
  static void cb_lbLoadSet(Fl_Browser*, void*);
public:
  Fl_HoverButton *btnAddLoad;
private:
  inline void cb_btnAddLoad_i(Fl_HoverButton*, void*);
  static void cb_btnAddLoad(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnRemoveLoad;
private:
  inline void cb_btnRemoveLoad_i(Fl_HoverButton*, void*);
  static void cb_btnRemoveLoad(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnEditLoad;
private:
  inline void cb_btnEditLoad_i(Fl_HoverButton*, void*);
  static void cb_btnEditLoad(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnAssignLoad;
private:
  inline void cb_btnAssignLoad_i(Fl_HoverButton*, void*);
  static void cb_btnAssignLoad(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnClearElements;
private:
  inline void cb_btnClearElements_i(Fl_HoverButton*, void*);
  static void cb_btnClearElements(Fl_HoverButton*, void*);
public:
  void show();
  void setLoadSet(ElementLoadSet* loadSet);
  ElementLoadSet* getLoadSet();
  void hide();
private:
  void fillListBox();
public:
  BeamLoad* getCurrentLoad();
  void setFemWidget(void* femWidget);
};
#endif
