// generated by Fast Light User Interface Designer (fluid) version 1.0100

#ifndef LoadsDlg_h
#define LoadsDlg_h
#include <FL/Fl.H>
#define MR_OK 0
#define MR_CANCEL 1
#include <FemBeamMaterialSet.h>
#include <FL/fl_message.h>
#include "MaterialDlg.h"
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Browser.H>

class CMaterialsDlg {
  CFemBeamMaterialSet* m_materials;
  Fl_Widget* m_workspace;
  CFemBeamMaterial* m_currentMaterial;
public:
  CMaterialsDlg();
  Fl_Window *wndMaterials;
  Fl_Button *btnClose;
private:
  inline void cb_btnClose_i(Fl_Button*, void*);
  static void cb_btnClose(Fl_Button*, void*);
public:
  Fl_Browser *lbMaterials;
private:
  inline void cb_lbMaterials_i(Fl_Browser*, void*);
  static void cb_lbMaterials(Fl_Browser*, void*);
public:
  Fl_Button *btnAddMaterial;
private:
  inline void cb_btnAddMaterial_i(Fl_Button*, void*);
  static void cb_btnAddMaterial(Fl_Button*, void*);
public:
  Fl_Button *btnRemoveMaterial;
private:
  inline void cb_btnRemoveMaterial_i(Fl_Button*, void*);
  static void cb_btnRemoveMaterial(Fl_Button*, void*);
public:
  Fl_Button *btnEditMaterial;
private:
  inline void cb_btnEditMaterial_i(Fl_Button*, void*);
  static void cb_btnEditMaterial(Fl_Button*, void*);
public:
  void show();
  void setMaterials(CFemBeamMaterialSet* materials);
  CFemBeamMaterialSet* getMaterials();
  void setWorkspace(Fl_Widget* widget);
  void hide();
private:
  void fillListBox();
public:
  CFemBeamMaterial* getCurrentMaterial();
};
#endif
