// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef NodeLoadsDlg_h
#define NodeLoadsDlg_h
#include <FL/Fl.H>
#define MR_OK 0
#define MR_CANCEL 1
#include <FL/fl_message.H>
#include <FemNodeLoadSet.h>
#include <FemBeamNodeLoad.h>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Browser.H>
#include "Fl_HoverButton.h"

class NodeLoadsDlg {
  CFemNodeLoadSet* m_loadSet;
  void* m_femWidget;
  CFemBeamNodeLoad* m_currentLoad;
public:
  NodeLoadsDlg();
  Fl_Double_Window *wndNodeLoads;
  Fl_Browser *lbLoadSet;
private:
  inline void cb_lbLoadSet_i(Fl_Browser*, void*);
  static void cb_lbLoadSet(Fl_Browser*, void*);
public:
  Fl_HoverButton *btnAddLoad;
private:
  inline void cb_btnAddLoad_i(Fl_HoverButton*, void*);
  static void cb_btnAddLoad(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnRemoveLoad;
private:
  inline void cb_btnRemoveLoad_i(Fl_HoverButton*, void*);
  static void cb_btnRemoveLoad(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnEditLoad;
private:
  inline void cb_btnEditLoad_i(Fl_HoverButton*, void*);
  static void cb_btnEditLoad(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnAssignLoad;
private:
  inline void cb_btnAssignLoad_i(Fl_HoverButton*, void*);
  static void cb_btnAssignLoad(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnClearElements;
private:
  inline void cb_btnClearElements_i(Fl_HoverButton*, void*);
  static void cb_btnClearElements(Fl_HoverButton*, void*);
public:
  void show();
  void setLoadSet(CFemNodeLoadSet* loadSet);
  CFemNodeLoadSet* getLoadSet();
  void hide();
private:
  void fillListBox();
public:
  CFemBeamNodeLoad* getCurrentLoad();
  void setFemWidget(void* femWidget);
};
#endif
