site_name: ObjectiveFrame - An interactive beam analysis tool
repo_url: https://github.com/jonaslindemann/objectiveframe

nav:
- Home: index.md
- About: about.md
- Download: download.md
- Use: use.md
- Develop: develop.md
- Links: links.md
- Blog: 
  - blog/index.md
  - 2022:
    - blog/2022/version_b2_released.md

- Contact: contact.md

theme: 
  name: material
  palette:
    scheme: youtube
    #primary: LU
    #accent: LU
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant    
    - navigation.tracking
    - navigation.section
    - navigation.tabs
    - navigation.top
    - header.autohide
  custom_dir: overrides    

extra_css:
  - stylesheets/extra.css   

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta

extra:
  blog:
    dir: blog
    author: Jonas Lindemann
    author_image: https://avatars.githubusercontent.com/u/9675453
    words_read_per_minute: 300
    list_length: 25
    extended_preview: true



