add_subdirectory(fem)
add_subdirectory(visfem)
add_subdirectory(util)
add_subdirectory(ofai)
add_subdirectory(ofai_test)
add_subdirectory(ofmath)
add_subdirectory(ofui)
add_subdirectory(objframe)
add_subdirectory(ofsolve)
add_subdirectory(ofsolver)
add_subdirectory(imguifd)
add_subdirectory(civetweb)
add_subdirectory(ofservice)
